apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170506261
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170506261
    app.kubernetes.io/part-of: test-app-170506261
  name: java-quarkus-170506261
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170506261
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170506261
    spec:
      containers:
      - image: quay.io/hacdev/qc35iznq-tenant/test-app-170506261/java-quarkus-170506261@sha256:f413baa0146ef77d41b4c5e6fa6c453bb4eb12e538fbdb4cbde222ff914eace5
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
